### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by gingerbeardman** [Vinnl/feeds#12]
I simply don't get the expected/advertised experience or results. 

No feeds in my GitHub pages.

**Comment by Vinnl** [comment]
Hi @gingerbeardman, did you follow all the steps [here](https://feed-me-up-scotty.vincenttunru.com/docs/automate)? Specifically:

> - Create a new branch called gh-pages.
> - Under the Actions tab, enable Workflows for your fork.
> - Make sure the Publishing Source for your GitHub Pages site is set to the gh-pages branch. [Instructions here.](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site)

**Comment by gingerbeardman** [comment]
Yes, I did. At least, unless I've made a mistake somehow. 

At the root of my GH pages url I see the readme.

At /feeds/funfacts.xml I see a 404. 

Am I misunderstanding something?

**Comment by gingerbeardman** [comment]
Digging a bit more.

Dupe of #9 

![Screen shot 2023-08-22 at 13 26 36](https://github.com/Vinnl/feeds/assets/49612/282dcb86-bd0a-47d5-8b13-a3c50adc026a)
