### ISSUE TITLE
Update documentation with how to setup pages

### ISSUE THREAD

**Issue by CeleritasCelery** [Vinnl/feeds#2]
Thanks for the great product! I was following the github instructions on https://feed-me-up-scotty.vincenttunru.com/docs/automate but I couldn't get the results to show up at `https://<username>.github.io/feeds/<feedname>.xml`. After doing a lot of digging, I realized I had to go to `Settings`, `Pages`, and then set the `Source` to be the `gh-pages` branch. Otherwise it would not work. I think it would be valuable to update the documentation.

**Comment by Vinnl** [comment]
Thanks @CeleritasCelery! I was under the impression that that was the default publishing source, but I've updated the readme and project site to explicitly mention this as something to check, so hopefully others won't struggle with this in the future. Let me know if you have further suggestions/requests!
