### ISSUE TITLE
It doesn't work. browserType.launch Issue

### ISSUE THREAD

**Issue by amblerkr** [Vinnl/feeds#4]
Run npx feed-me-up-scotty || npx feed-me-up-scotty || npx feed-me-up-scotty
npm WARN exec The following package was not found and will be installed: feed-me-up-scotty
browserType.launch: Executable doesn't exist at /home/runner/.cache/ms-playwright/firefox-1323/firefox/firefox
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers:              ║
║                                                                         ║
║     npx playwright install                                              ║
║                                                                         ║
║ <3 Playwright Team                                                      ║
╚═════════════════════════════════════════════════════════════════════════╝
    at fetchFeedData (file:///home/runner/.npm/_npx/fa12bb8499fb4525/node_modules/feed-me-up-scotty/dist/run.js:[6](https://github.com/BlerKR/feeds/runs/6435796189?check_suite_focus=true#step:4:6)0:35)
    at file:///home/runner/.npm/_npx/fa12bb8499fb4525/node_modules/feed-me-up-scotty/dist/run.js:12:36
    at async file:///home/runner/.npm/_npx/fa12bb8499fb4525/node_modules/feed-me-up-scotty/dist/run.js:11:2[7](https://github.com/BlerKR/feeds/runs/6435796189?check_suite_focus=true#step:4:7)
    at async file:///home/runner/.npm/_npx/fa12bb8499fb4525/node_modules/feed-me-up-scotty/dist/run.js:11:27
    at async file:///home/runner/.npm/_npx/fa12bb8499fb4525/node_modules/feed-me-up-scotty/dist/run.js:11:27
    at async file:///home/runner/.npm/_npx/fa12bb8499fb4525/node_modules/feed-me-up-scotty/dist/run.js:11:27
    at async file:///home/runner/.npm/_npx/fa12bb8499fb4525/node_modules/feed-me-up-scotty/dist/run.js:11:27
    at async run (file:///home/runner/.npm/_npx/fa12bb8499fb4525/node_modules/feed-me-up-scotty/dist/run.js:10:23) {
  name: 'Error'
}
browserType.launch: Executable doesn't exist at /home/runner/.cache/ms-playwright/firefox-1323/firefox/firefox
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers:              ║
║                                                                         ║
║     npx playwright install                                              ║
║                                                                         ║
║ <3 Playwright Team                                                      ║
╚═════════════════════════════════════════════════════════════════════════╝
    at fetchFeedData (file:///home/runner/.npm/_npx/fa12bb[8](https://github.com/BlerKR/feeds/runs/6435796189?check_suite_focus=true#step:4:8)499fb4525/node_modules/feed-me-up-scotty/dist/run.js:60:35)
    at file:///home/runner/.npm/_npx/fa12bb8499fb4525/node_modules/feed-me-up-scotty/dist/run.js:12:36
    at async file:///home/runner/.npm/_npx/fa12bb8499fb4525/node_modules/feed-me-up-scotty/dist/run.js:11:27
    at async file:///home/runner/.npm/_npx/fa12bb8499fb4525/node_modules/feed-me-up-scotty/dist/run.js:11:27
    at async file:///home/runner/.npm/_npx/fa12bb8499fb4525/node_modules/feed-me-up-scotty/dist/run.js:11:27
    at async file:///home/runner/.npm/_npx/fa12bb8499fb4525/node_modules/feed-me-up-scotty/dist/run.js:11:27
    at async file:///home/runner/.npm/_npx/fa12bb8499fb4525/node_modules/feed-me-up-scotty/dist/run.js:11:27
    at async run (file:///home/runner/.npm/_npx/fa12bb8499fb4525/node_modules/feed-me-up-scotty/dist/run.js:10:23) {
  name: 'Error'
}
browserType.launch: Executable doesn't exist at /home/runner/.cache/ms-playwright/firefox-1323/firefox/firefox
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers:              ║
║                                                                         ║
║     npx playwright install                                              ║
║                                                                         ║
║ <3 Playwright Team                                                      ║
╚═════════════════════════════════════════════════════════════════════════╝
    at fetchFeedData (file:///home/runner/.npm/_npx/fa12bb84[9](https://github.com/BlerKR/feeds/runs/6435796189?check_suite_focus=true#step:4:9)9fb4525/node_modules/feed-me-up-scotty/dist/run.js:60:35)
    at file:///home/runner/.npm/_npx/fa12bb8499fb4525/node_modules/feed-me-up-scotty/dist/run.js:12:36
    at async file:///home/runner/.npm/_npx/fa12bb8499fb4525/node_modules/feed-me-up-scotty/dist/run.js:11:27
    at async file:///home/runner/.npm/_npx/fa12bb8499fb4525/node_modules/feed-me-up-scotty/dist/run.js:11:27
    at async file:///home/runner/.npm/_npx/fa12bb8499fb4525/node_modules/feed-me-up-scotty/dist/run.js:11:27
    at async file:///home/runner/.npm/_npx/fa12bb8499fb4525/node_modules/feed-me-up-scotty/dist/run.js:11:27
    at async file:///home/runner/.npm/_npx/fa12bb8499fb4525/node_modules/feed-me-up-scotty/dist/run.js:11:27
    at async run (file:///home/runner/.npm/_npx/fa12bb8499fb4525/node_modules/feed-me-up-scotty/dist/run.js:[10](https://github.com/BlerKR/feeds/runs/6435796189?check_suite_focus=true#step:4:10):[23](https://github.com/BlerKR/feeds/runs/6435796189?check_suite_focus=true#step:4:23)) {
  name: 'Error'
}
Error: Process completed with exit code 1.

**Comment by mfclarke-ts** [comment]
This fixed it for me: https://github.com/Vinnl/feeds/pull/5

**Comment by Vinnl** [comment]
Should be fixed with @mfclarke-ts's fix, which is now merged into this repository. You may have to apply the same fix to your fork; you can do so by copying [these contents](https://github.com/Vinnl/feeds/blob/main/.github/workflows/pages.yml) over to the file `.github/workflows/pages.yml` in your own fork. Apologies for the inconvenience.
