### ISSUE TITLE
TimeoutError

### ISSUE THREAD

**Issue by sonofevil** [Vinnl/feeds#8]
The page I wanna turn into a feed uses javascript to load its content, so I'm not too surprised it's causing trouble, but still I'd like to understand why exactly it happens:

```page.goto: Timeout 60000ms exceeded.
=========================== logs ===========================
navigating to "https://www.metal-archives.com/release/upcoming", waiting until "domcontentloaded"
============================================================
    at fetchPageEntries (file:///home/runner/.npm/_npx/fa12bb8499fb4525/node_modules/feed-me-up-scotty/dist/run.js:123:16)
    at file:///home/runner/.npm/_npx/fa12bb8499fb4525/node_modules/feed-me-up-scotty/dist/run.js:80:39
    at async fetchFeedData (file:///home/runner/.npm/_npx/fa12bb8499fb4525/node_modules/feed-me-up-scotty/dist/run.js:78:25)
    at async file:///home/runner/.npm/_npx/fa12bb8499fb4525/node_modules/feed-me-up-scotty/dist/run.js:12:30
    at async run (file:///home/runner/.npm/_npx/fa12bb8499fb4525/node_modules/feed-me-up-scotty/dist/run.js:10:23) {
  name: 'TimeoutError'
}
```

The page loads in my browser just fine.

**Comment by Vinnl** [comment]
Hi @sonofevil, you can try setting [the `waitUntil` option](https://feed-me-up-scotty.vincenttunru.com/docs/setup#waituntil) to `load` or `networkidle` to see if that is better adapted to the website's loading pattern?

**Comment by sonofevil** [comment]
Now I get this 

```remote: Permission to sonofevil/metallum-rss.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/sonofevil/metallum-rss.git/': The requested URL returned error: 403
Error: Process completed with exit code 128.
```

???

**Comment by Vinnl** [comment]
Unfortunately that one is a bit more problematic; [403 stands for "Forbidden"](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_client_errors), and presumably means that the website is trying to prevent automated visits? It might be that a retry might resolve it.

Btw, looking at the site, I see that it can be a bit slow fetching the results. You could also try specifically waiting for results to appear after executing JavaScript, with:

```toml
waitForSelector = "#upcomingAlbumList tr.odd"
```

**Comment by sonofevil** [comment]
That doesn't seem to change anything, unfortunately. What confuses me is that it says `unable to access 'https://github.com/sonofevil/metallum-rss.git/'`.

Maybe I should try gitlab.

**Comment by Vinnl** [comment]
Ah! Sorry, I missed that it was actually referring to your repository instead of the source website. Hmm, in that case, you could check whether you've set up GitHub Pages to publish from the `gh-pages` branch, as per [these docs](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-from-a-branch)? And maybe you could check if there are any particular [restrictions on that branch](https://github.com/sonofevil/metallum-rss/settings/branches) that prevent GitHub Actions from pushing to it? And otherwise indeed maybe GitLab might work.

**Comment by sonofevil** [comment]
There don't seem to be any restrictions.

But it works perfectly on GitLab.

Thanks for the help.

**Comment by Vinnl** [comment]
Good to hear!
